name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-12.0.dev <4.0.0'

dependencies:
  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  http: ^1.0.0
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
