// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArVBHjd_Hm09Qg13y8TduXHlmkiUzZVtQ',
    appId: '1:350541721117:web:a15a8fd8e9a447965720f4',
    messagingSenderId: '350541721117',
    projectId: 'firetest-302b8',
    authDomain: 'firetest-302b8.firebaseapp.com',
    databaseURL: 'https://firetest-302b8-default-rtdb.firebaseio.com',
    storageBucket: 'firetest-302b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5oMu7v6XJVOGz29eDr9rUCTkgbfuwSA4',
    appId: '1:350541721117:android:43825935fc7a51775720f4',
    messagingSenderId: '350541721117',
    projectId: 'firetest-302b8',
    databaseURL: 'https://firetest-302b8-default-rtdb.firebaseio.com',
    storageBucket: 'firetest-302b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6_36zs3ST3pOHGlWfCdrxn8kMssf_Rfs',
    appId: '1:350541721117:ios:42dbcdf6d6f55b555720f4',
    messagingSenderId: '350541721117',
    projectId: 'firetest-302b8',
    databaseURL: 'https://firetest-302b8-default-rtdb.firebaseio.com',
    storageBucket: 'firetest-302b8.appspot.com',
    iosClientId: '350541721117-u35aul2shjtspe4vdsjgau04eis6u5s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firesotreTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6_36zs3ST3pOHGlWfCdrxn8kMssf_Rfs',
    appId: '1:350541721117:ios:df640402b48928645720f4',
    messagingSenderId: '350541721117',
    projectId: 'firetest-302b8',
    databaseURL: 'https://firetest-302b8-default-rtdb.firebaseio.com',
    storageBucket: 'firetest-302b8.appspot.com',
    iosClientId: '350541721117-q1agunlrpruqt02634stunh47677858q.apps.googleusercontent.com',
    iosBundleId: 'com.example.firesotreTest.RunnerTests',
  );
}
